### PR TITLE
Implemented RANDOM values.

### PR DESCRIPTION
**Pull request by MatteoTondelli**
This is an alternative of #63 pull request which will work both for properties and queries, as suggested by @MatthieuDartiailh.
Additionally multiple values can be generated, this way result of a DMM scan can be simulated.

The syntax is this: `RANDOM(min, max, num_of_results) {...}`.
The output type can only be **numerical**.

### CODE REVIEW

**Comment by MatthieuDartiailh** [comment]
This looks interesting ! 

Could you:
- fix the conflict 
- add some documentation (in particular your error mentions it)

As a side note did you consider generating integer in addition to float ?

**Comment by MatteoTondelli** [comment]
Ok, I will fix the conflicts and add some documentation.
Actually there's no need to generate integer because you can already convert the output with the string formatter `{:d}`.

**Comment by MatthieuDartiailh** [comment]
Would that work for sequences though ? 
Anyway I am thinking about binary block that likely require a different mechanism anyway.

**Comment by MatthieuDartiailh** [comment]
To properly support sequences, we should be able to specify a separator (as a fourth argument ?). I think RANDOM is fine. We can complexify the parsing logic later to allow to select the type and separator. But let's land this first before over engineering things.

**Comment by MatteoTondelli** [comment]
I've just resolved the conflicts and added a few lines of documentation.
I was not able to compile the documentation myself...

**Comment by MatthieuDartiailh** [comment]
Looking at the example I wonder if it would not make more sense to specify the RAMDOM directive within the `{}` to avoid conflict between a surrounding message and data generation. WDYT ?

**Comment by MatteoTondelli** [comment]
Yes, definetely cleaner. I will change it and redo the commit.

**Comment by MatteoTondelli** [comment]
Previous regex would have worked both for RANDOM directive inside and outside the curled brackets, now it's strictly searched inside.

**Comment by MatthieuDartiailh** [comment]
Thanks ! Could you add some tests ?

A bunch of linting failures are unrelated to your changes and I can take care of fixing them before merging if you want.

**Comment by MatteoTondelli** [comment]
I will try but I'm very inexperienced with testing... I will try my best.

**Comment by MatthieuDartiailh** [comment]
Let me know if you want me to take over. It may just take me some time to get to this.

**Comment by MatteoTondelli** [comment]
I've added some tests, had bit troubles handling the random.seed(). Not the cleanest code, but I think this is something.
What do you think? Is this enough for testing?

**Comment by MatthieuDartiailh** [comment]
It looks good. I am just bothered by the fact that the validity of the query is checked only when it is used. But that is likely a large problem than this PR.
Do you mind if I fix the linting part here so that you do not need to rebase after ?

**Comment by MatteoTondelli** [comment]
Yes, not the strongest implementation from this side.
Of course, you can fix the linting.

**Comment by MatthieuDartiailh** [comment]
I created #97 to address the linting. Once it goes in I will rebase your branch

**Comment by MatthieuDartiailh** [comment]
Thanks for your contribution !

**Pull request merged**
