### PR TITLE
pyvisa-sim moved to pyvisa organization

### PR DESCRIPTION
**Pull request by skrchnavy**
organization was changed from hgrecco to pyvisa

related: pyvisa/pyvisa#265 and pyvisa/pyvisa#294

### CODE REVIEW

**Comment by MatthieuDartiailh** [comment]
You missed some occurrences in the README and the docs.

**Comment by skrchnavy** [comment]
Thanks, updated

**Comment by MatthieuDartiailh** [comment]
Merging.

bors r+

**Comment by MatthieuDartiailh** [comment]
Why did you close ?

**Comment by skrchnavy** [comment]
I deleted accidentally branch sooner then needed.

**Comment by MatthieuDartiailh** [comment]
Bors managed to finish the job apparently. You are safe to delete the branch again.

**Pull request closed without merging**
