### PR TITLE
Feature/modernize

### PR DESCRIPTION
**Pull request by croesnick**
As it turned out, the codebase which passed travis tests two years ago do not successfully test in travis anymore end of 2019. In an attempt to fix them, I also took the liberty to update tox and its interaction with travis, switched from unittest to pytest (to enable smarter test fixtures to even test more of this package's functionality in the future), and sprinkled some more modern touches (like pyproject.toml). Hope you like it. :)

### CODE REVIEW

**Comment by MatthieuDartiailh** [comment]
Sorry for the delay. I have quite busy recently and since I was never truly convinced by the approach taken by pyvisa-sim it went under my radar. Your changes looks fine so I am gonna merge. Thanks for your contribution.

bors r+

**Comment by MatthieuDartiailh** [comment]
PyYAML seems to not be available anymore on 3.4.  @croesnick  could you remove it from the build matrix ? Anyway Pyvisa will drop support for Python 2 and support only Python 3.6+ onward like many other projects these days.

**Comment by croesnick** [comment]
@MatthieuDartiailh: Seems like we had a "good" timing as PyYAML dropped support for Python 3.4 in version 5.3. As PyVISA still seems to support Python 3.4 in its most recent version, I suggest to simply pin PyYAML to version <5.3.

**Comment by MatthieuDartiailh** [comment]
Bors r+

**Pull request merged**
