### PR TITLE
Check for existence of GPIB secondary address

### LINKED ISSUE #58: PyVISA 1.12.0 and GPIB Secondary Addresses
PyVISA 1.12.0 introduced a change to how GPIB secondary addresses are handled.  An undefined secondary address is now returned as a [None instead of "0"](https://github.com/pyvisa/pyvisa/blob/main/pyvisa/rname.py#L354).  This [breaks pyvisa-sim](https://github.com/pyvisa/pyvisa-sim/blob/33de1e4a2466d210cc038c305637f3933454eb92/pyvisa_sim/gpib.py#L27) when loading a GPIB instrument address that does not contain a secondary address, raising `TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'`

I'm not sure what the best solution would be for pyvisa-sim.  My personal workaround is to just define a secondary address in my test cases.
  
Example:
```
> rm = pyvisa.highlevel.ResourceManager("@sim")
> inst = rm.open_resource("GPIB::1::INSTR")
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>  
  File "./python3.10/site-packages/pyvisa/highlevel.py", line 3284, in open_resource
    res.open(access_mode, open_timeout)  
  File "./python3.10/site-packages/pyvisa/resources/resource.py", line 278, in open
    self.session, status = self._resource_manager.open_bare_resource(
  File "./python3.10/site-packages/pyvisa/highlevel.py", line 3209, in open_bare_resource
    return self.visalib.open(self.session, resource_name, access_mode, open_timeout)  
  File "./python3.10/site-packages/pyvisa_sim/highlevel.py", line 121, in open
    sess = cls(session, resource_name, parsed)
  File "./python3.10/site-packages/pyvisa_sim/sessions.py", line 79, in __init__
    self.after_parsing()
  File "./python3.10/site-packages/pyvisa_sim/gpib.py", line 33, in after_parsing
    self.attrs[constants.VI_ATTR_GPIB_SECONDARY_ADDR] = int(self.parsed.secondary_address)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```

### PR DESCRIPTION
**Pull request by Satertek**
Check for existence of GPIB secondary address prior setting VI_ATTR_GPIB_SECONDARY_ADDR attribute
Resolves #58

### CODE REVIEW

**Comment by MatthieuDartiailh** [comment]
Actually VISA defines `VI_NO_SEC_ADDR` that should be returned if there is no secondary address so you could add an else branch.

**Comment by Satertek** [comment]
Added, and ended up just reusing [this](https://github.com/pyvisa/pyvisa/blob/645c1c648870dac4caffa2c65241638ef273f981/pyvisa/rname.py#L772) block of code to keep it under the column limit :smiley:

**Comment by MatthieuDartiailh** [comment]
Thanks !

**Comment by jenshnielsen** [comment]
Would it be possible to get a release to pypi that includes this fix?

**Comment by MatthieuDartiailh** [comment]
I will do my best to do it later this week. Feel free to ping me if you see nothing.

**Comment by MatthieuDartiailh** [comment]
The release is on  PyPI

**Pull request merged**
